### ISSUE TITLE
Aes encrypted error

### ISSUE THREAD

**Issue by colinkim** [artem-karpenko/archiver-zip-encrypted#16]
I want simply to encrypt to already existing zip.(zip includes another zip files)
so I make following this code.(level: 0)
archiver.registerFormat('zip-encrypted', require("archiver-zip-encrypted"));
 let archive = archiver.create('zip-encrypted', {zlib: {level: 0}, encryptionMethod: 'aes256', password: '123'});
 archive.append(fs.readFileSync(item.filepath), {name: backupZip})
archive.finalize();
 let out = fs.createWriteStream(dir+'/'+'aes123.zip');
archive.pipe(out);

but this code did not work (with error)
(I got "error Central and local directory mismatch of file "20180406.zip" (crc-32-local: 0 hex central: 8456155C hex" using winzip ).

If I change level: 0 to 1 then source zip file is damaged(source file 1gb change to xx.mb)

**Comment by artem-karpenko** [comment]
Hi @colinkim,
there is indeed an issue with 'store' compression (level=0) if file is archived from the Buffer (i.e. like in your example when it's read via readFileSync). I will work on fixing it. level=0 is also buggy, so it needs to be fixed. Hope fully soon I will provide a fix.

However, issue is not reproduced for me if level=1 or higher is used.
I noticed that you read file completely into memory via `readFileSync`, this may cause memory issues for large files (like 1GB as you mentioned). Did you try using `createReadStream` instead? 

Also please make sure that nodejs process is running till the end of compression process - f.e. if it's not a web-server but just a script launched from command line, it's possible that script is ended before compression is completed.

**Comment by artem-karpenko** [comment]
I published new version which should fix behavior with 'store' compression and buffers. Could you please try updating (version 1.0.5) and trying again?

**Comment by colinkim** [comment]
I updated libary but it is not working 
Still not compressed correctly.(1.1g file change to 100byte)
Am I wrong coding something?(because I have little experience with JavaScript and nodejs.)
Maybe it's asynchronous processing problem.
Please refer following code(I refer your test code)
let archive = archiver.create('zip-encrypted', {zlib: {level: 1}, encryptionMethod: 'aes256', password: '123'});
        archive.append(fs.createReadStream('/Users/kimcy/dev/nodejs/archiver-zip-encrypted-master/test/resources/20180406.zip' ), { // with stream
            name: '20180406.zip'
        });
 archive.finalize();
 let out = fs.createWriteStream('/Users/kimcy/dev/nodejs/archiver-zip-encrypted-master/test/resources/20180406.zip');
        archive.pipe(out);

        out.on('close', () => {
            
            done();
  });
If you want to get my testfile(20180406.zip) I can send this.

**Comment by colinkim** [comment]
It is work. Thank you 
By the way I press ctrl+'c key then restart it(while it is processed) then 
it is printed "events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Users/kimcy/dev/nodejs/archiver-zip-encrypted-master/test/resources/20180406.zip'"
I don't know what's wrong 
please refer following code.
let archive = archiver.create('zip-encrypted', {zlib: {level: 1}, encryptionMethod: 'aes256', password: '123'});
        archive.append(fs.createReadStream('/Users/kimcy/dev/nodejs/archiver-zip-encrypted-master/test/resources/20180406.zip' ), { // with stream
            name: '20180406.zip'
        });

        archive.finalize(); //promise
        archive.on('pipe', () => {
            console.log('pipe');
        });

        archive.on('progress', () => {
            console.log('pipe');
        });

        archive.on('close', ()=>{
            console.log('read finsih');
        });

        let out = fs.createWriteStream('/Users/kimcy/dev/nodejs/archiver-zip-encrypted-master/test/resources/aes.zip');
        archive.pipe(out);

        out.on('close', () => {
            console.log("done ");
        
            var end = new Date().getTime();
            var diff = end - start;

            console.log('time is = ',diff);
        });

**Comment by artem-karpenko** [comment]
Hi @colinkim,
yes, your code works for me. Looks like the issue is resolved?
